services:
  aegis-gateway:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - SERVICE_NAME=aegis-gateway
      - POLICY_DIR=/app/policies
      - LOGS_DIR=/app/logs
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production
      - ADMIN_API_KEY=admin-key-change-in-production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/policies:/app/policies
    depends_on:
      - otel-collector
    networks:
      - aegis-network

  admin-ui:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
    depends_on:
      - aegis-gateway
    networks:
      - aegis-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics
    depends_on:
      - jaeger
    networks:
      - aegis-network

  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - aegis-network

networks:
  aegis-network:
    driver: bridge
